version: '3.8'
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://database:27017
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6378
    ports:
      - '8888:8888'
    depends_on:
      - database
      - redis

  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6378:6379'
